version: 2
updates:
    - package-ecosystem: "gitsubmodule"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "deps"
      open-pull-requests-limit: 10
