name: Sync Vencord

env:
    UPSTREAM_URL: "https://github.com/Vendicated/Vencord.git"
    WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    UPSTREAM_BRANCH: "main"
    DOWNSTREAM_BRANCH: ""

on:
    schedule:
        - cron: "0 23 * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Sync Vencord
              uses: verticalsync/sync-upstream-repo@master
              with:
                  upstream_repo: ${{ env.UPSTREAM_URL }}
                  upstream_branch: ${{ env.UPSTREAM_BRANCH }}
                  downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
                  token: ${{ env.WORKFLOW_TOKEN }}
